---
- name: Get cloudformation info from stack
  import_playbook: get-hosts.yml

# Create K8s deployment
- name: Create or redeploy on K8s minikube 
  hosts: just_created
  tasks:
  - name: Check if app is deployed
    shell: kubectl get deployment hello-node
    register: deployed
    ignore_errors: yes
  
  - debug: var=deployed.stdout_lines

  - debug: var=deployed

  - name: Create deployment
    shell: /usr/local/bin/kubectl create deployment hello-node --image=gcr.io/hello-minikube-zero-install/hello-node 
    register: kubectl
    become: yes
    # when: kubectl get services/kubernetes-bootcamp -o go-template='{{(index .spec.ports 0).nodePort}}' 

  - debug: var=kubectl.stdout_lines

  - name: Expose deployment
    shell: /usr/local/bin/kubectl expose deployment hello-node --type=LoadBalancer --port=8080
    register: kubectl
    become: yes

  - debug: var=kubectl.stdout_lines

  - name: Get services
    shell: /usr/local/bin/kubectl get services
    register: kubectl
    become: yes

  - debug: var=kubectl.stdout_lines

  - name: Publish service
    shell: /usr/local/bin/minikube service hello-node
    register: minikube 
    become: yes

  - debug: var=kubectl.stdout_lines